name: Build pg-deploy

on:
  push:
    paths:
      - database/**

jobs:
  run-build-sh:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./database
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Make the script files executable
        run: chmod +x build.sh
      - name: Run a script
        run: ./build.sh
      - name: Save pgdeploy file
        uses: actions/upload-artifact@v4
        with:
          name: pgdeploy
          path: ./database/pg_deploy.sql
      - name: Move file
        run: mv pg_deploy.sql ../cli/dataforge/resources/
      - name: Commit file
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
        shell: bash
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
